# Generated by Django 3.0.8 on 2020-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('set_number', models.IntegerField()),
                ('rep_number', models.IntegerField()),
                ('video_link', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='day added')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('calorie', models.IntegerField()),
                ('protein_amount', models.IntegerField()),
                ('carbohydrate_amount', models.IntegerField()),
                ('fat_amount', models.IntegerField()),
                ('date_added', models.DateTimeField(verbose_name='day added')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
                ('body_mass_index', models.FloatField()),
                ('daily_calorie_intakes', models.IntegerField()),
                ('daily_burned_calories', models.IntegerField()),
                ('daily_protein_intake', models.IntegerField()),
                ('daily_carbohydrate_intake', models.IntegerField()),
                ('daily_fat_intake', models.IntegerField()),
                ('required_carbohydrate', models.IntegerField()),
                ('required_protein', models.IntegerField()),
                ('required_fat', models.IntegerField()),
                ('neck', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('hip', models.IntegerField()),
            ],
        ),
    ]
