# Generated by Django 3.0.8 on 2020-07-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(to='pages.Exercise'),
        ),
        migrations.AddField(
            model_name='user',
            name='foods',
            field=models.ManyToManyField(to='pages.Food'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_mail',
            field=models.EmailField(max_length=100),
        ),
    ]
