# Generated by Django 3.0.8 on 2020-07-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200709_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body_fat_percentage',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_mass_index',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_burned_calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_calorie_intakes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_carbohydrate_intake',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_fat_intake',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_protein_intake',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='pages.Exercise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foods',
            field=models.ManyToManyField(blank=True, to='pages.Food'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hip',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='neck',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='required_carbohydrate',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='required_fat',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='required_protein',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='waist',
            field=models.IntegerField(blank=True),
        ),
    ]
