# Generated by Django 3.0.8 on 2020-07-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200709_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='how_many_calorie_burn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='purpose_of_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='exercises',
            field=models.ManyToManyField(to='pages.Exercise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foods',
            field=models.ManyToManyField(to='pages.Food'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
