# Generated by Django 3.0.8 on 2020-07-10 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_auto_20200710_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('purpose_of_user', models.IntegerField(default=0)),
                ('body_fat_percentage', models.FloatField(null=True)),
                ('body_mass_index', models.FloatField(null=True)),
                ('daily_calorie_intakes', models.IntegerField(null=True)),
                ('daily_burned_calories', models.IntegerField(null=True)),
                ('daily_protein_intake', models.IntegerField(null=True)),
                ('daily_carbohydrate_intake', models.IntegerField(null=True)),
                ('daily_fat_intake', models.IntegerField(null=True)),
                ('required_carbohydrate', models.IntegerField(null=True)),
                ('required_protein', models.IntegerField(null=True)),
                ('required_fat', models.IntegerField(null=True)),
                ('neck', models.IntegerField(null=True)),
                ('waist', models.IntegerField(null=True)),
                ('hip', models.IntegerField(null=True)),
                ('exercises', models.ManyToManyField(to='pages.Exercise')),
                ('foods', models.ManyToManyField(to='pages.Food')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
