# Generated by Django 3.0.8 on 2020-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200710_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='purpose_of_user',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='user_mail',
        ),
        migrations.AddField(
            model_name='fitnessperson',
            name='purpose_of_use',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'I want to keep my weight.'), (1, 'I want to lose weight.'), (2, 'I want to gain weight')], null=True),
        ),
    ]
