# Generated by Django 3.0.8 on 2020-07-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200710_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessperson',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female')]),
        ),
    ]
