# Generated by Django 3.0.8 on 2020-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200710_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessperson',
            name='body_fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='body_mass_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_burned_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_calorie_intakes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_carbohydrate_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_fat_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_protein_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='hip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='neck',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='purpose_of_use',
            field=models.PositiveSmallIntegerField(choices=[(0, 'I want to keep my weight.'), (1, 'I want to lose weight.'), (2, 'I want to gain weight')], null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='required_carbohydrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='required_fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='required_protein',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='waist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
