# Generated by Django 3.0.8 on 2020-07-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200710_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessperson',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='pages.Exercise'),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='foods',
            field=models.ManyToManyField(blank=True, to='pages.Food'),
        ),
    ]
