# Generated by Django 3.0.8 on 2020-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200710_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='day added'),
        ),
    ]
