# Generated by Django 3.0.8 on 2020-07-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200710_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='recipe_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='day added'),
        ),
    ]
