# Generated by Django 3.0.8 on 2020-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_food_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
