# Generated by Django 3.0.8 on 2020-07-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200710_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessperson',
            name='exercises',
        ),
        migrations.AddField(
            model_name='fitnessperson',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Exercise'),
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='foods',
        ),
        migrations.AddField(
            model_name='fitnessperson',
            name='foods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Food'),
        ),
    ]
