# Generated by Django 3.0.8 on 2020-07-13 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0015_auto_20200713_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_person_use', to=settings.AUTH_USER_MODEL),
        ),
    ]
