# Generated by Django 3.0.8 on 2020-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20200713_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessperson',
            name='first_name',
            field=models.CharField(default='empty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessperson',
            name='last_name',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
