# Generated by Django 3.0.8 on 2020-07-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200713_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessperson',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='last_name',
        ),
    ]
