# Generated by Django 3.0.8 on 2020-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_exercise_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cardio'), (1, 'Weight Exercise')], default=0),
        ),
    ]
