# Generated by Django 3.0.8 on 2020-07-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_exercise_exercise_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Cardio'), (1, 'Weight Exercise')], default=1),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rep_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='set_number',
            field=models.IntegerField(default=0),
        ),
    ]
