# Generated by Django 3.0.8 on 2020-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200714_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrate_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_amount',
            field=models.FloatField(),
        ),
    ]
