# Generated by Django 3.0.8 on 2020-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200717_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='day added'),
        ),
    ]
