# Generated by Django 3.0.8 on 2020-07-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_exercise_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessperson',
            name='daily_required_calorie_intakes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
