# Generated by Django 3.0.8 on 2020-07-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_fitnessperson_daily_required_calorie_intakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_calorie_intakes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_carbohydrate_intake',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_fat_intake',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='daily_protein_intake',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
