# Generated by Django 3.0.8 on 2020-07-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20200723_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
