# Generated by Django 3.0.8 on 2020-07-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_exercise_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='rep_number',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='set_number',
        ),
    ]
