# Generated by Django 3.0.8 on 2020-07-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_auto_20200723_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='how_many_calorie_burn',
        ),
    ]
