# Generated by Django 3.0.8 on 2020-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_exercise_how_many_calorie_burn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='how_many_calorie_burn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
