# Generated by Django 3.0.8 on 2020-07-27 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20200724_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calorie_intakes', models.IntegerField(blank=True, default=0)),
                ('daily_burned_calories', models.IntegerField(blank=True, null=True)),
                ('daily_protein_intake', models.IntegerField(blank=True, default=0)),
                ('daily_carbohydrate_intake', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='day added')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='how_many_calorie_burn',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep_number',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='daily_burned_calories',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='daily_calorie_intakes',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='daily_carbohydrate_intake',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='daily_protein_intake',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='exercise_programs',
        ),
        migrations.RemoveField(
            model_name='fitnessperson',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='fitness_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.FitnessPerson'),
        ),
        migrations.AddField(
            model_name='meal',
            name='fitness_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.FitnessPerson'),
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseprogram',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='day added'),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fitnessperson',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='day added'),
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=0)),
                ('rep_number', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('how_many_calorie_burn', models.IntegerField(default=0)),
                ('exercise', models.ManyToManyField(to='pages.Exercise')),
                ('exercise_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ExerciseProgram')),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.FitnessPerson')),
            ],
        ),
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now=True, null=True, verbose_name='day added')),
                ('daily_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.DailyPerson')),
                ('fitness_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.FitnessPerson')),
            ],
        ),
        migrations.AddField(
            model_name='dailyperson',
            name='fitness_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.FitnessPerson'),
        ),
        migrations.AddField(
            model_name='exerciseprogram',
            name='daily_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.DailyPerson'),
        ),
        migrations.AddField(
            model_name='meal',
            name='diet_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.DietProgram'),
        ),
    ]
