# Generated by Django 3.0.8 on 2020-07-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20200727_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperson',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day added'),
        ),
        migrations.AlterField(
            model_name='dietprogram',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day added'),
        ),
        migrations.AlterField(
            model_name='exerciseprogram',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day added'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='day added'),
        ),
    ]
