# Generated by Django 3.0.8 on 2020-07-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_auto_20200727_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperson',
            name='daily_burned_calories',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
