# Generated by Django 3.0.8 on 2020-07-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20200727_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessperson',
            name='daily_fat_intake',
        ),
        migrations.AddField(
            model_name='dailyperson',
            name='daily_fat_intake',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
