# Generated by Django 3.0.8 on 2020-07-27 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_auto_20200727_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietprogram',
            name='fitness_user',
        ),
        migrations.RemoveField(
            model_name='exerciseprogram',
            name='fitness_user',
        ),
    ]
